# Generated by Django 3.1.7 on 2021-02-27 15:03

import ckeditor_uploader.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_security_app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Why_Choose_Us_section',
            new_name='Why_Choose_Us_background',
        ),
        migrations.AlterField(
            model_name='header_navbar',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='latest_news_post',
            name='news_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='our_approach_section',
            name='short_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='Service_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
